version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb+srv://saurabhjojare:mealdashprod%23123@mealdash-db.mus56qs.mongodb.net/food_delivery?retryWrites=true&w=majority&appName=mealdash-db"
      JWT_SECRET: "358c13e4fa6974bf3d258768cc0b724725639bde5413893f9d66dc747f6e0327"
      STRIPE_API_KEY: ""
      PAYPAL_API_KEY: ""
