services:
  mongo:
    image: mongo:8.0.9
    container_name: mealdash-mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: mealdash-app
    ports:
      - 8080:8080
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/mealdashdatabase

volumes:
  mongo-data:
